Add Alerts on OpsGenie
edreanernst/node-red-contrib-opsgenie pull request #1
Opened 2021-03-10 03:13 UTC by ptorrezao

Hi Adrian, thanks for the initiative.

The expansion was the implementation of the GET method for the Alerts endpoint, retrieving 1 message per alert.

The purpose of the expansion is to start including the OpsGenie on my home automation stuff.
Yep, the notifications on the APP and/or the call aren't enough :)

Jokes aside, one of the use cases is turn on of the Lights/turn on the coffee maker when I receive an alert.
All of this without waking up the kid, or annoy too much the wife.
This is helpful for me, it may be helpful for some else.

2021-03-12 13:42 UTC, edreanernst commented
Hi @ptorrezao !

Thanks for contributing! The capability to retrieve alerts is very valuable. I like your use case!

However, it would be better if we didn't create a separate node for that. Instead we should extend the current OpsgenieAlert node to handle that functionality so that the OpsgenieAlert node eventually may handle all aspects of the Opsgenie `/alerts` API endpoint. That way we minimise the number of different nodes to be used.

I will appreciate it if you could adapt your contribution by making the necessary changes to the existing node :
- new getAlerts() method in opsgenie_api.js (which you already have done)
- new case for the `msg.action` switch called `get`
- change opsgenie_alert.html to change `outputs:1`
- document the usage (with an example) in opsgenie_alert.html
- documentation changes to README.md

Feel free to update this Pull Request after making the necessary changes.

Thanks again for your willingness to contribute!

2021-03-12 15:02 UTC, ptorrezao commented
Hi @edreanernst,

In fairness I don't agree with having one single Node for all of the Interactions, but yet the project is yours so you're calling the shots. 😃 
I think opsgenie_api.js should cover every interaction(and it is) with the API and each node tackle the specific of the interaction.
Really believe on separation of concerns.
But hey I will refactor to fall into your requirements.

2021-03-12 15:42 UTC, edreanernst commented
The original idea was to have one node per endpoint which is also the way I described it in the README. The problem is you can keep separating concerns until you have too many different nodes. It makes sense to group some concerns together. It's a balancing act.

I am warming up to the idea of having separate nodes for sending data to Opsgenie and for receiving data from Opsgenie. In other words, for each API endpoint you will have two nodes - one for reading and one for writing.

We will then have to change the naming at least of the current OpsgenieAlert node to something like OpsgenieAlertsWrite, and then your contributed node to something like OpsgenieAlertsRead. I'll have a proper look at it as soon as I can.

In the meantime, don't refactor yet. I'm also open to more suggestions if you have any.

2021-03-12 16:01 UTC, ptorrezao commented
The requirement documentation is still valid thought 🤦‍♂️ 
No the next couple days(or weeks) I will do that at least.

But regarding the "Grand Scheme" I do understand that would be hard to keep track of a API Client on nodered, so we should run away for having on node for Close Alert, Open Alert. (Would be nice but its unmanageable, on my opinion).
But one Node for GET actions and another for POST/PUT I think its bearable.

2021-03-15 15:02 UTC, edreanernst commented
Hi @ptorrezao ,

Hope all is well.

I have made some minor changes to the existing Alert node, basically renaming it to Opsgenie Alert Action. The purpose of the existing node would then be for all alert actions that need to be taken. The new node which you are contributing here would then be called Opsgenie Alert Read, which can be used to get all alerts.

I suggest you pull in the latest master commit. If you could then just name the new node as mentioned above and make the necessary documentation changes, I would then be happy to look at an updated pull request.

Thanks for your effort so far!

2021-03-16 23:33 UTC, ptorrezao commented
Hi @edreanernst ,

Since the vision is have only 1 node per action, I refactor the node to accept the action so in the future this node can be complemented (e.g. Get Specific alert)

2021-03-17 10:14 UTC, edreanernst requested changes
Please also add detailed documentation to the opsgenie_alert_read.html file. Please see opsgenie_alert_action.html for reference.

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +    - [Read Action](#alert-reader)
```suggestion
    - [Alert Read](#alert-reader)
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +### Alert Reader
```suggestion
### Alert Read
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +This node will pull the existing alerts from your OpsGennie Setup according the configuration.
```suggestion
This node will pull the existing alerts from your Opsgenie setup according the configuration.
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +This is a string field where an the type of question is can be specified (e.g. alerts)
```suggestion
This is a string field where the type of action can be specified (e.g. list)
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +* "alerts"
```suggestion
* "list"
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +  * When trigered, this type will retreive the alerts from the [Alerts API Endpoint](https://docs.opsgenie.com/docs/alert-api#list-alerts) producing on message per alert.
```suggestion
  * When triggered, this action will retrieve a list of the alerts from the [Alerts API Endpoint](https://docs.opsgenie.com/docs/alert-api#list-alerts) producing one message per alert.
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +    "action": "alerts"
```suggestion
    "action": "list"
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +#### Example of an Msg produced per Alert
```suggestion
#### Example of a message produced per alert
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +  "event_type": "OpsGenie Alert",
```suggestion
  "event_type": "Opsgenie Alert",
```

2021-03-17 10:14 UTC, edreanernst commented on README.md
> +  "topic": "OpsGenie Alert",
```suggestion
  "topic": "Opsgenie Alert",
```

2021-03-17 10:14 UTC, edreanernst commented on package.json
> +        "name": "Edrean Ernst;Pedro Torrezão"
"author" field should include only one person, while "contributors" may be an array of persons
```suggestion
        "name": "Edrean Ernst"
```

2021-03-17 10:14 UTC, edreanernst commented on package.json
>      },
```suggestion
    },
    "contributors": [
        {
            "name": "Pedro Torrezão"
        }
    ]
```

2021-03-17 10:14 UTC, edreanernst commented on package.json
> +    "version": "0.1.1",
I will change the version later
```suggestion
    "version": "0.1.0",
```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.html
> +        icon: "font-awesome/fa-bell",
Let's keep all the alert nodes the same in terms of icon
```suggestion
        icon: "alert.png",

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.html
> +        <label for="node-input-name"><i class="fa fa-tag"></i> Name</label>
```suggestion
        <label for="node-input-name"><i class="icon-tag"></i> Name</label>

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.html
> +    <p>A node that retreives Opsgenie Alerts and turn them into messages (1 per alert)</p>
```suggestion
    <p>A node that retrieves Opsgenie alerts and turn them into messages (1 per alert)</p>

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                node.error("No configurations defined!");
```suggestion
                node.error("No configuration defined!");

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                case 'alerts':
```suggestion
                case 'list':

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                                        event_type: "OpsGenie Alert",
```suggestion
                                        event_type: "Opsgenie Alert",

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                                        topic: "OpsGenie Alert",
```suggestion
                                        topic: "Opsgenie Alert",

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                                node.error("There was a problem reading an Opsgenie alerts: '" + aResult.error + "' - " + JSON.stringify(aResult.body));
```suggestion
                                node.error("There was a problem reading the Opsgenie alerts: '" + aResult.error + "' - " + JSON.stringify(aResult.body));

```

2021-03-17 10:14 UTC, edreanernst commented on src/opsgenie_alert_read.js
> +                        node.error("There was a problem reading an Opsgenie alerts: '" + error.message + "'");
```suggestion
                        node.error("There was a problem reading the Opsgenie alerts: '" + error.message + "'");

```

2021-03-17 19:05 UTC, ptorrezao commented
Hi @edreanernst,
I did the changes that you requested. Sent it to review again.
Sorry for the grammar errors, the only excuse that I have is the fact that I'm not an Native Speaker (🤷‍♂️poor excuse, I know🤷‍♂️)

2021-03-29 13:03 UTC, edreanernst approved these changes

2021-03-29 13:06 UTC, edreanernst commented
Thanks again @ptorrezao for the contribution! Sorry for the delay in processing the PR.

I have accepted and merged your contribution. You should see an official release soon.

Thanks again and any further contributions will be most welcome.

2021-03-29 13:06 UTC, merged